(function attachWeaponProficiencies(globalScope) {
  const WEAPON_PROFICIENCIES = [
    ['Axe', 'When attacking with an axe, if your wound attempt fails, you may ignore it and attempt to wound the selected hit location again.\n\nLimit, once per attack.', 'When an Axe Master wounds a monster with an axe at a location with a persistent injury, that wound becomes a critical wound.\n\nAll survivors gain Axe Specialization in addition to their other weapon proficiencies.'],
    ['Bow', 'When attacking with a bow, you may reroll any misses once.\n\nLimit, once per attack.', 'If you are a Bow Master, all bows in your gear grid gain Deadly 2. In addition, ignore cumbersome on all bows.\n\nAll survivors gain Bow Specialization in addition to their other weapon proficiencies.'],
    ['Cleaver', 'You can use Cleaver Proficiency while Frenzy.\n\nWhen attacking with a cleaver, ignore one wound reaction during that attack.', 'At the end of your attack with a cleaver, suffer the Frenzy brain trauma.\n\nWhen attacking with a cleaver, if you draw a Trap, discard five other drawn Monster Hit Location Cards to cancel the trap and shuffle it back into the deck.'],
    ['Club', "When attacking with a club, on a Perfect hit, double your wound attempt total on the first selected hit location.\n\nLimit, once per attack.", "When a Club Master attacks with a club, if a successful wound attempt total is greater than or equal to twice the monster's toughness, inflict an additional wound.\n\nAll survivors gain Club Specialization in addition to their other weapon proficiencies."],
    ['Dagger', 'When attacking with a Dagger, if a wound attempt fails, after performing any reactions, you may discard another drawn hit location card to attempt to wound the failed hit location again.\n\nLimit, once per attack.', 'After a wounded hit location is discarded, a Dagger Master who is adjacent to the attacker and the wounded monster may spend 1 survival to re-draw the wounded hit location and attempt to wound with a dagger. Treat monster reactions on the re-drawn hit location card normally.\n\nAll survivors gain Dagger Specialization in addition to their other weapon proficiencies.'],
    ['Fan', 'At the start of your act, you may lose all deflect tokens.\n\nAt the end of your act, if you are standing and have a fan in your gear grid, you may Deflect 1 for free.', 'While you have no deflect tokens, fans in your gear grid gain Sharp and Devastating 1. While you have deflect tokens, increase the range of your Perfect hits with fans by 2.'],
    ['Fist & Tooth', "You may stand (if knocked down) at the start of the monster's turn or the survivor's turn.\n\nLimit, once per round.", 'While a survivor is a Fist & Tooth Master, they gain +2 permanent accuracy and +2 permanent strength (they receive this bonus even when not attacking with Fist & Tooth).\n\nAll survivors gain Fist & Tooth Specialization in addition to their other weapon proficiencies.'],
    ['Grand Weapon', 'When attacking with a grand weapon, gain +1 accuracy.\n\nWhen attacking with a grand weapon during your act, if you critically wound, the monster is knocked down.', 'When a Grand Weapon Master perfectly hits with a grand weapon, cancel all reactions for that attack.\n\nAll survivors gain Grand Weapon Specialization in addition to their other weapon proficiencies.'],
    ['Katana', 'You may not select this as your weapon type.\n\nIf you are blind and have 4+ levels of Katana proficiency, gain the following:\n\nOn your first Perfect hit each attack with a Katana, do not draw a hit location. The monster suffers 1 wound.', "When a survivor reaches Katana Mastery, they leave the settlement forever, heeding the call of the storm to hone their art.\n\nBefore the master leaves, you may nominate a survivor. Set that survivor's weapon type to Katana and their weapon proficiency level to 1."],
    ['Katar', 'When attacking with a katar, cancel reactions on the first selected hit locations.', 'If you are a Katar Master, gain a +1 evasion token on a Perfect hit with a katar. When you are knocked down, remove all +1 evasion tokens.\n\nAll survivors gain Katar Specialization in addition to their other weapon proficiencies.'],
    ['Scythe', 'When you critically wound with a scythe, roll 1d10. On a 6+, shuffle the hit location deck (do not shuffle unresolved hit locations).\n\nLimit, once per round.', "At the start of a Scythe Master's act, if they are insane, they gain +1 survival, which they may only spend to activate scythes."],
    ['Shield', 'While a shield is in your gear grid, you are no longer knocked down after Collision with a monster.\n\nWhile a shield is in your gear grid, add 1 Armor to all hit locations.', 'When a Shield Master is adjacent to a survivor that is targeted by a monster, they may swap spaces on the board with the survivor and become the target instead. The master must have a shield to perform this.\n\nAll survivors gain Shield Specialization in addition to their other weapon proficiencies.'],
    ['Spear', 'When attacking with a spear, if you draw a trap, roll 1d10. On a 7+, cancel the trap. Discard it, then reshuffle the hit location discard into the hit location deck and draw a new card.\n\nLimit, once per round.', 'Whenever a Spear Master hits a monster with a spear, they may spend 1 survival to gain the priority target token. If they made the hit from directly behind another survivor, that survivor gains the priority target token instead.\n\nAll survivors gain Spear Specialization in addition to their other weapon proficiencies.'],
    ['Sword', 'When attacking with a sword, after drawing hit locations, make a wound attempt and then select a hit location to resolve with that result.\n\nLimit, once per attack.', 'A Sword Master gains +1 accuracy, +1 strength, and +1 speed when attacking with a Sword.\n\nAll survivors gain Sword Specialization in addition to their other weapon proficiencies.'],
    ['Twilight Sword', 'This sentient sword improves as it is used. Gain the following effects as its proficiency rank increases:\n\nRank 2: Ignore Cumbersome on Twilight Sword.\nRank 4: When attacking with the Twilight Sword, ignore slow and gain +2 speed.\nRank 6: Twilight Sword gains deadly.', "Any survivor who attains Twilight Sword Mastery leaves the settlement forever in pursuit of a higher purpose. Remove them from the settlement's population.\n\nYou may place the master's Twilight Sword in another survivor's gear grid or archive it."],
    ['Whip', 'When you wound with a whip, instead of moving the top card of the AI deck into the wound stack, you may move the top card of the AI discard pile.\n\nLimit, once per attack.', 'Whip Masters gain +5 strength when attacking with a whip.\n\nAll survivors gain Whip Specialization in addition to their other weapon proficiencies.'],
    ['Willow', 'Swords in your gear grid gain Block 1 and the two-handed keyword.\n\nWhen you block or deflect a hit with a sword, gain +1 survival.\n\nLimit once per round.', "After resolving a monster's attack, if you ignored a hit with a block or deflect, you may spend 1 survival to activate a sword and attack.\n\nLimit once per round."]
  ].map(([name, specialization, mastery]) => Object.freeze({ name, specialization, mastery }))

  const byName = new Map(WEAPON_PROFICIENCIES.map(item => [item.name.toLocaleLowerCase(), item]))

  function getWeaponProficiency(name) {
    return byName.get(String(name || '').trim().toLocaleLowerCase()) || null
  }

  const api = Object.freeze({ WEAPON_PROFICIENCIES: Object.freeze(WEAPON_PROFICIENCIES), getWeaponProficiency })
  globalScope.KDMWeaponProficiencies = api
  if (typeof module !== 'undefined' && module.exports) module.exports = api
})(typeof window !== 'undefined' ? window : globalThis)
